// Code generated by wit-bindgen-go. DO NOT EDIT.

package sub

// Exports represents the caller-defined exports from "component:subtractor/sub".
var Exports struct {
	// Sub represents the caller-defined, exported function "sub".
	//
	//	sub: func(a: u32, b: u32) -> u32
	Sub func(a uint32, b uint32) (result uint32)
}
