// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package random represents the imported interface "wasi:random/random@0.2.0".
package random

// GetRandomU64 represents the imported function "get-random-u64".
//
//	get-random-u64: func() -> u64
//
//go:nosplit
func GetRandomU64() (result uint64) {
	result0 := wasmimport_GetRandomU64()
	result = (uint64)((uint64)(result0))
	return
}
